

# local/dev 환경
spring:
  datasource:
    url: //url
    username: //username
    password: //passowrd
    driver-class-name: //driver
    hikari:
      connection-timeout: 3000
      validation-timeout: 3000
      minimum-idle: 3
      max-lifetime: 240000
      maximum-pool-size: 10 

logging:
  level:
    org.hibernate.SQL: info
    root: info
    com.zaxxer.hikari.pool.HikariPool: debug
      

# cloud(dr) 환경